### PR TITLE
Introduce semantic release

### PR DESCRIPTION
**Pull request by simonseyock**
## Description

This PR enables semantic-release. It also adds `commitlint` to the test phase.

Releases will be triggered manually.

## Pull request type

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Tests
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the 
  [Apache Licence Version 2.0](https://github.com/terrestris/shogun/blob/main/LICENSE).
- [x] I have followed the [guidelines for contributing](https://github.com/terrestris/shogun/blob/main/CONTRIBUTING.md).
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/terrestris/shogun/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added or updated tests and documentation, and the test suite passes (run `mvn test` locally).
- [ ] I have added a screenshot/screencast to illustrate the visual output of my update.

### CODE REVIEW

**Comment by simonseyock** [comment]
An example of a successful run can be seen here: https://github.com/simonseyock/shogun/actions/runs/3931590468/jobs/6723047913

This contains some steps that where removed now, but especially the semantic-release step is the same.

**Comment by simonseyock** [comment]
Proper authentication configuration is still missing. Refer to:
* https://github.com/semantic-release/github#github-authentication
* https://github.com/cycjimmy/semantic-release-action#basic-usage

**Comment by simonseyock** [comment]
There is still a problem with the jib `mainClass`. It does not find one for the shogun-config project. This has to be checked.

**Comment by simonseyock** [comment]
I added the `skip` option for jib for `shogun-lib`, `shogun-config` and `shogun-manager`.

A successful build can be seen here: https://github.com/simonseyock/shogun/actions/runs/3937478695/jobs/6735050478

**Review by dnlkoch — APPROVED** [review]
Very nice!

**Pull request merged**
