### PR TITLE
Introduces findAllBy in BaseService

### PR DESCRIPTION
**Pull request by KaiVolland**
~~This introduces the possibility to call the `findAll` method with a `Specification`.~~

This introduces the `findAllBy` method which can be called with a `Specification`.

This may replace the currently outcommented functions `findBy` and `findByFilter`. If the majority of the devs aggree id remove these commented lines.

### CODE REVIEW

**Comment by dnlkoch** [comment]
Generally approved, but sementically I would prefer to have an additional signature like 
```
getAllBy(Specification specification)
```

**Comment by KaiVolland** [comment]
> Generally approved, but sementically I would prefer to have an additional signature like
> 
> ```
> getAllBy(Specification specification)
> ```

Any specific reason why? To enhance readability and make code clearer? Or is there anything bad about that polymorphic stuff?

**Comment by dnlkoch** [comment]
Yes, just because for better readability, but it's not a blocker and no, there is nothing bad about the polymorphism. You decide.

**Comment by KaiVolland** [comment]
Already refactored it. I was just curious. :)

**Comment by KaiVolland** [comment]
> LGTM, however I would prefer to user interfaces in repositories wherever it is possible.

Our repositories extend the `JpaSpecificationExecutor` interface which provides this functionality.

**Pull request merged**
